export const heroWebGPUPostProcessingConfig = {
  chromaticAberration: {
    angle: 0.32,
    angleDrift: 0.05,
    angleDriftSpeed: 0.16,
    pointerAngleInfluence: 0.05,
    idleAmount: 0.00008,
    idleBlend: 0.014,
    impactAmountBoost: 0.0015,
    impactBlendBoost: 0.42,
    emergenceAmountBoost: 0.00034,
    emergenceBlendBoost: 0.11,
    maxBlend: 0.52,
    reducedMotionScale: 0.68,
    viewportStrength: {
      desktop: 1,
      laptop: 0.9,
      tablet: 0.76,
      mobile: 0.58,
    },
    membrane: {
      center: { x: 0.516, y: 0.494 },
      pointerParallaxX: 0.012,
      pointerParallaxY: 0.01,
      innerRadius: 0.028,
      outerRadius: 0.2,
      exponent: 1.46,
      weightFloor: 0.18,
      weightBoost: 0.92,
    },
    object: {
      centerStart: { x: 0.546, y: 0.506 },
      centerEnd: { x: 0.626, y: 0.492 },
      pointerParallaxX: 0.016,
      pointerParallaxY: 0.012,
      innerRadius: 0.024,
      outerRadius: 0.16,
      exponent: 1.34,
      weightFloor: 0.02,
      weightBoost: 0.34,
    },
  },
  volumetricLighting: {
    field: {
      position: { x: 0.14, y: 0.72, z: -2.2 },
      size: { x: 8.4, y: 5.6, z: 4.1 },
      intensity: {
        idle: 0.18,
        membraneBoost: 0.56,
        objectBoost: 0.2,
        max: 0.94,
      },
      smoke: {
        idle: 1.2,
        membraneBoost: 0.64,
        objectBoost: 0.18,
        max: 2.1,
      },
      noise: {
        repeat: 4.6,
        scale: 9.6,
        coarseScale: 0.11,
        mediumScale: 0.052,
        fineScale: 0.024,
        driftX: 0.05,
        driftZ: 0.018,
        driftSecondaryZ: 0.012,
      },
    },
    lights: {
      cool: {
        color: "#8eb6ff",
        width: 1.55,
        height: 4.8,
        intensity: 5.8,
        volumetricIntensity: 8.4,
        orbitCenter: { x: -0.72, y: 0.48, z: -2.4 },
        orbitAmount: { x: 0.4, y: 0.28, z: 0.34 },
        lookAt: { x: 0.08, y: 0.16, z: -0.24 },
        motion: {
          speed: 0.18,
          phase: 0.18,
          verticalPhase: 0.6,
          targetDrift: 0.16,
        },
        response: {
          membraneBoost: 0.54,
          objectBoost: 0.12,
          pointerX: 0.14,
          pointerY: 0.1,
        },
      },
      warm: {
        color: "#c9a27f",
        width: 1.18,
        height: 4.2,
        intensity: 4.1,
        volumetricIntensity: 6.6,
        orbitCenter: { x: 1.06, y: 0.32, z: -2.52 },
        orbitAmount: { x: 0.34, y: 0.22, z: 0.28 },
        lookAt: { x: 0.52, y: 0.04, z: -0.12 },
        motion: {
          speed: -0.13,
          phase: 1.42,
          verticalPhase: 0.18,
          targetDrift: 0.12,
        },
        response: {
          membraneBoost: 0.24,
          objectBoost: 0.3,
          pointerX: 0.08,
          pointerY: 0.08,
        },
      },
    },
    qualityProfiles: {
      desktop: {
        enabled: true,
        resolutionScale: 0.34,
        steps: 12,
        blurAmount: 0.72,
        textureSize: 72,
        volumeIntensityScale: 1,
        smokeScale: 1,
        motionScale: 1,
      },
      laptop: {
        enabled: true,
        resolutionScale: 0.3,
        steps: 10,
        blurAmount: 0.62,
        textureSize: 64,
        volumeIntensityScale: 0.9,
        smokeScale: 0.92,
        motionScale: 0.88,
      },
      tablet: {
        enabled: true,
        resolutionScale: 0.26,
        steps: 8,
        blurAmount: 0.52,
        textureSize: 48,
        volumeIntensityScale: 0.72,
        smokeScale: 0.78,
        motionScale: 0.68,
      },
      mobile: {
        enabled: false,
        resolutionScale: 0.22,
        steps: 6,
        blurAmount: 0.42,
        textureSize: 40,
        volumeIntensityScale: 0,
        smokeScale: 0,
        motionScale: 0,
      },
    },
    reducedMotion: {
      volumeIntensityScale: 0.78,
      smokeScale: 0.88,
      motionScale: 0.45,
      blurAmount: 0.5,
    },
  },
  headline3D: {
    lines: [
      { text: "We make brands", y: 0.22 },
      { text: "belong in Rust.", y: -0.16 },
    ],
    placement: {
      position: { x: 0.08, y: 1.08, z: -2.2 },
      rotation: { x: -0.08, y: -0.16, z: -0.02 },
    },
    material: {
      color: "#d8d6d2",
      roughness: 0.34,
      metalness: 0.44,
      clearcoat: 0.18,
      clearcoatRoughness: 0.22,
      envMapIntensity: 0.72,
      opacity: 0.18,
      coolLift: "#8fa8ca",
      warmLift: "#c8a387",
    },
    motion: {
      floatX: 0.028,
      floatY: 0.022,
      rotateY: 0.035,
      parallaxX: 0.06,
      parallaxY: 0.04,
      membraneBoost: 0.05,
      objectBoost: 0.03,
    },
    qualityProfiles: {
      desktop: {
        enabled: true,
        size: 0.24,
        depth: 0.075,
        curveSegments: 9,
        bevelEnabled: true,
        bevelThickness: 0.008,
        bevelSize: 0.006,
        bevelSegments: 4,
        scale: 1,
        opacityScale: 1,
      },
      laptop: {
        enabled: true,
        size: 0.22,
        depth: 0.066,
        curveSegments: 7,
        bevelEnabled: true,
        bevelThickness: 0.007,
        bevelSize: 0.005,
        bevelSegments: 3,
        scale: 0.94,
        opacityScale: 0.9,
      },
      tablet: {
        enabled: true,
        size: 0.19,
        depth: 0.052,
        curveSegments: 5,
        bevelEnabled: false,
        bevelThickness: 0,
        bevelSize: 0,
        bevelSegments: 0,
        scale: 0.8,
        opacityScale: 0.72,
      },
      mobile: {
        enabled: false,
        size: 0.18,
        depth: 0.04,
        curveSegments: 4,
        bevelEnabled: false,
        bevelThickness: 0,
        bevelSize: 0,
        bevelSegments: 0,
        scale: 0.7,
        opacityScale: 0,
      },
    },
    reducedMotion: {
      opacityScale: 0.9,
      motionScale: 0.4,
    },
  },
};
