export const heroConfig = {
  renderer: {
    exposure: 1.01,
  },
  quality: {
    laptopBreakpoint: 1440,
    tabletBreakpoint: 980,
    mobileBreakpoint: 680,
  },
  responsive: {
    desktop: {
      pixelRatioCap: 1.45,
      antialias: true,
      rendererPrecision: "highp",
      environmentMode: "exr",
      sphereDetail: {
        widthSegments: 88,
        heightSegments: 66,
      },
    },
    laptop: {
      pixelRatioCap: 1.2,
      antialias: true,
      rendererPrecision: "highp",
      environmentMode: "exr",
      sphereDetail: {
        widthSegments: 72,
        heightSegments: 54,
      },
    },
    tablet: {
      pixelRatioCap: 0.95,
      antialias: false,
      rendererPrecision: "mediump",
      environmentMode: "room",
      sphereDetail: {
        widthSegments: 52,
        heightSegments: 40,
      },
    },
    mobile: {
      pixelRatioCap: 0.8,
      antialias: false,
      rendererPrecision: "mediump",
      environmentMode: "room",
      sphereDetail: {
        widthSegments: 36,
        heightSegments: 28,
      },
    },
  },
  palette: {
    background: "#050507",
    fog: "#07080b",
    chrome: "#eef2f7",
    silver: "#d8dee7",
    cool: "#6d85b3",
    coolEdge: "#b8d1ff",
    graphite: "#4c555f",
    graphiteSpecular: "#b8c4d2",
    graphiteEmissive: "#181d24",
    warm: "#8f7460",
  },
  camera: {
    desktop: {
      fov: 35,
      position: { x: 0.06, y: 0.08, z: 7.15 },
    },
    laptop: {
      fov: 38,
      position: { x: 0.05, y: 0.08, z: 7.65 },
    },
    tablet: {
      fov: 42,
      position: { x: 0.04, y: 0.08, z: 8.35 },
    },
    mobile: {
      fov: 47,
      position: { x: 0.02, y: 0.06, z: 9.1 },
    },
    lookAt: { x: 0.1, y: -0.18, z: 0.05 },
  },
  intro: {
    duration: 1.5,
    ease: "power3.out",
    startPosition: { x: 0, y: -0.14, z: 0.9 },
    startRotation: { x: 0.05, y: -0.08, z: -0.01 },
    stageScale: 0.97,
  },
  sphere: {
    radius: 0.24,
    widthSegments: 88,
    heightSegments: 66,
    idleFloatAmplitude: 0.01,
    idleFloatSpeed: 0.56,
  },
  sphereStream: {
    initialLeadLane: "mid",
    leadLaneOrder: ["mid", "upperMid", "mid", "low"],
    lanes: {
      low: {
        startOffset: { x: -1.02, y: -0.38, z: 0.12 },
        nearOffset: { x: -0.18, y: -0.1, z: 0.07 },
        crossOffset: { x: -0.03, y: -0.03, z: 0.03 },
        hiddenOffset: { x: -0.01, y: -0.02, z: 0.01 },
        scale: 0.95,
        driftPhase: 0.18,
        driftBias: -0.015,
        arcLift: -0.012,
      },
      mid: {
        startOffset: { x: -1.14, y: -0.08, z: 0.05 },
        nearOffset: { x: -0.14, y: -0.02, z: 0.03 },
        crossOffset: { x: -0.01, y: 0, z: 0.01 },
        hiddenOffset: { x: 0, y: 0, z: 0 },
        scale: 1,
        driftPhase: 0.46,
        driftBias: 0,
        arcLift: 0.006,
      },
      upperMid: {
        startOffset: { x: -1.2, y: 0.12, z: -0.05 },
        nearOffset: { x: -0.2, y: 0.08, z: -0.02 },
        crossOffset: { x: -0.03, y: 0.04, z: -0.01 },
        hiddenOffset: { x: 0.01, y: 0.02, z: -0.01 },
        scale: 0.96,
        driftPhase: 0.84,
        driftBias: 0.014,
        arcLift: 0.014,
      },
    },
    motion: {
      leadDriftX: 0.016,
      leadDriftY: 0.009,
      leadDriftZ: 0.01,
      leadDriftSpeedX: 0.38,
      leadDriftSpeedY: 0.28,
      leadDriftSpeedZ: 0.22,
      leadTangentPull: 0.01,
      leadScalePulse: 0.006,
      leadScalePulseSpeed: 0.24,
      leadDriftFade: 0.52,
      approachOpacityFloor: 0.18,
      approachRevealEnd: 0.22,
      entryRevealStart: 0.08,
      entryRevealLength: 0.14,
    },
  },
  rustObject: {
    idleFloatAmplitude: 0.025,
    idleFloatSpeed: 0.52,
    material: {
      color: "#4c555f",
      emissive: "#181d24",
      emissiveIntensity: 0.02,
      metalness: 0.22,
      roughness: 0.38,
      clearcoat: 0.46,
      clearcoatRoughness: 0.2,
      sheen: 0.06,
      sheenColor: "#8f9db0",
      sheenRoughness: 0.46,
      specularIntensity: 0.88,
      specularColor: "#b8c4d2",
      ior: 1.42,
      envMapIntensity: 1.28,
      side: "double",
    },
  },
  membrane: {
    geometry: {
      body: {
        width: 1.82,
        height: 2.88,
        depth: 0.36,
        cornerRadius: 0.22,
        cornerSegments: 16,
        bevelSize: 0.024,
        bevelThickness: 0.058,
        bevelSegments: 5,
      },
      sweepBand: {
        width: 0.42,
        height: 2.54,
        radius: 0.16,
      },
      halo: {
        offsetX: 0.04,
        offsetY: 0.02,
        offsetZ: -0.5,
        scaleX: 2.84,
        scaleY: 4.18,
      },
      conversionVeil: {
        width: 0.88,
        height: 2.34,
        radius: 0.18,
        offsetX: 0.1,
        offsetY: 0.02,
        offsetZ: 0.26,
        travelX: 0.05,
      },
      conversionPulse: {
        width: 0.76,
        height: 2.02,
        radius: 0.16,
        offsetX: 0.04,
        offsetY: 0.02,
        offsetZ: 0.32,
        travelX: 0.08,
      },
    },
    appearance: {
      bodyColor: "#d7dfe7",
      rimColor: "#e7edf5",
      emissive: "#10151b",
      rimEmissive: "#111923",
      transmission: 0.56,
      thickness: 2.2,
      ior: 1.18,
      attenuationDistance: 0.72,
      attenuationColor: "#303845",
      metalness: 0.01,
      roughness: 0.28,
      clearcoat: 0.58,
      clearcoatRoughness: 0.18,
      specularIntensity: 0.94,
      opacity: 0.985,
      envMapIntensity: 0.68,
      emissiveIntensity: 0.0016,
      sheen: 0.01,
      sheenColor: "#e4eaf1",
      sheenRoughness: 0.88,
      idleRoughnessDrift: 0.005,
      idleTransmissionDrift: 0.006,
      idleAttenuationDrift: 0.014,
      idleEmissivePulse: 0.0006,
      rimMetalness: 0.05,
      rimRoughness: 0.22,
      rimClearcoat: 0.72,
      rimClearcoatRoughness: 0.24,
      rimOpacity: 0.18,
      rimEnvMapIntensity: 0.96,
      rimEmissiveIntensity: 0.004,
      rimSheen: 0.02,
      rimSheenColor: "#d9e2ee",
      rimSheenRoughness: 0.72,
    },
    motion: {
      pointerYaw: 0.012,
      pointerPitch: 0.01,
      phaseYaw: 0.016,
      verticalDrift: 0.008,
      verticalDriftSpeed: 0.24,
      secondaryVerticalDrift: 0.003,
      secondaryVerticalDriftSpeed: 0.12,
      lateralDriftX: 0.01,
      lateralDriftSpeed: 0.17,
      depthDriftZ: 0.007,
      depthDriftSpeed: 0.14,
      idlePitch: 0.012,
      idlePitchSpeed: 0.22,
      idleYaw: 0.016,
      idleYawSpeed: 0.16,
      idleRoll: 0.012,
      idleRollSpeed: 0.11,
      idleRollPhase: 0.6,
      idleScaleBreath: 0.0035,
      idleScaleSpeed: 0.21,
      bandTravelX: 0.06,
      bandBob: 0.003,
      haloDriftX: 0.012,
      haloDriftY: 0.016,
      haloPulseSpeed: 0.19,
    },
    activation: {
      bandBaseOpacity: 0.008,
      bandIdleOpacity: 0.002,
      bandPulseOpacity: 0.04,
      bandWidthBoost: 0.05,
      bandHeightBoost: 0.025,
      bandDepthBoost: 0.024,
      haloBaseOpacity: 0.008,
      haloIdleOpacity: 0.004,
      haloPulseOpacity: 0.022,
      haloScaleXBoost: 0.2,
      haloScaleYBoost: 0.32,
      bodyThicknessBoost: 0.14,
      bodyEnvBoost: 0.04,
      bodyEmissiveBoost: 0.004,
      bodyScaleBoost: 0.014,
      bodyRoughnessBoost: 0.009,
      bodyTransmissionDip: 0.012,
      veilOpacity: 0.16,
      veilScaleBoost: 0.06,
      pulseOpacity: 0.045,
      pulseScaleBoost: 0.07,
      rimOpacityBoost: 0.05,
      rimEnvBoost: 0.05,
      rimScaleBoost: 0.022,
      rimRoughnessBoost: 0.015,
    },
    qualityProfiles: {
      desktop: {
        appearance: {
          side: "front",
        },
        dynamics: {},
      },
      laptop: {
        appearance: {
          transmission: 0.34,
          thickness: 1.5,
          clearcoat: 0.42,
          clearcoatRoughness: 0.22,
          envMapIntensity: 0.52,
          sheen: 0.01,
          side: "front",
          rimOpacity: 0.15,
          rimEnvMapIntensity: 0.78,
          rimClearcoat: 0.5,
          rimClearcoatRoughness: 0.28,
          rimSheen: 0,
        },
        dynamics: {
          transmissionFloor: 0.22,
          idleTransmissionDriftScale: 0.5,
          bodyTransmissionDipScale: 0.5,
          bodyThicknessBoostScale: 0.55,
          bodyEnvBoostScale: 0.6,
          bodyEmissiveBoostScale: 0.85,
          rimEnvBoostScale: 0.65,
          rimOpacityBoostScale: 0.75,
          rimEmissiveBoostScale: 0.7,
        },
      },
      tablet: {
        appearance: {
          transmission: 0.08,
          thickness: 0.45,
          clearcoat: 0.16,
          clearcoatRoughness: 0.32,
          envMapIntensity: 0.3,
          sheen: 0,
          side: "front",
          rimOpacity: 0.11,
          rimEnvMapIntensity: 0.54,
          rimClearcoat: 0.3,
          rimClearcoatRoughness: 0.36,
          rimSheen: 0,
        },
        dynamics: {
          transmissionFloor: 0,
          idleTransmissionDriftScale: 0.12,
          bodyTransmissionDipScale: 0.16,
          bodyThicknessBoostScale: 0.18,
          bodyEnvBoostScale: 0.28,
          bodyEmissiveBoostScale: 0.6,
          rimEnvBoostScale: 0.38,
          rimOpacityBoostScale: 0.46,
          rimEmissiveBoostScale: 0.56,
        },
      },
      mobile: {
        appearance: {
          transmission: 0,
          thickness: 0.12,
          clearcoat: 0.06,
          clearcoatRoughness: 0.38,
          envMapIntensity: 0.18,
          sheen: 0,
          side: "front",
          rimOpacity: 0.08,
          rimEnvMapIntensity: 0.32,
          rimClearcoat: 0.16,
          rimClearcoatRoughness: 0.42,
          rimSheen: 0,
        },
        dynamics: {
          transmissionFloor: 0,
          idleTransmissionDriftScale: 0,
          bodyTransmissionDipScale: 0,
          bodyThicknessBoostScale: 0.06,
          bodyEnvBoostScale: 0.14,
          bodyEmissiveBoostScale: 0.45,
          rimEnvBoostScale: 0.22,
          rimOpacityBoostScale: 0.28,
          rimEmissiveBoostScale: 0.44,
        },
      },
    },
  },
  chamber: {
    desktop: {
      membrane: {
        position: { x: 0.24, y: -0.08, z: 0.19 },
        rotation: { x: 0.15, y: -0.22, z: 0.07 },
        scale: { x: 0.92, y: 0.92, z: 0.92 },
      },
      sphere: {
        startX: -3.72,
        startY: 0.14,
        startZ: 0.32,
        nearX: -1.1,
        nearY: 0.09,
        nearZ: 0.16,
        crossX: -0.1,
        crossY: 0,
        crossZ: -0.04,
        hiddenX: 0.12,
        hiddenY: -0.04,
        hiddenZ: -0.12,
      },
      object: {
        startX: 0.22,
        startY: -0.06,
        startZ: -0.12,
        restX: 1.76,
        restY: -0.02,
        restZ: 0.1,
        holdX: 2.22,
        holdY: 0.02,
        holdZ: 0.13,
        exitX: 2.72,
        exitY: -0.08,
        exitZ: -0.04,
      },
    },
    laptop: {
      membrane: {
        position: { x: 0.2, y: -0.1, z: 0.19 },
        rotation: { x: 0.15, y: -0.2, z: 0.07 },
        scale: { x: 0.88, y: 0.88, z: 0.88 },
      },
      sphere: {
        startX: -3.36,
        startY: 0.12,
        startZ: 0.3,
        nearX: -1,
        nearY: 0.08,
        nearZ: 0.15,
        crossX: -0.08,
        crossY: 0,
        crossZ: -0.04,
        hiddenX: 0.11,
        hiddenY: -0.04,
        hiddenZ: -0.12,
      },
      object: {
        startX: 0.19,
        startY: -0.06,
        startZ: -0.12,
        restX: 1.62,
        restY: -0.03,
        restZ: 0.08,
        holdX: 2.02,
        holdY: 0.01,
        holdZ: 0.11,
        exitX: 2.46,
        exitY: -0.09,
        exitZ: -0.05,
      },
    },
    tablet: {
      membrane: {
        position: { x: 0.16, y: -0.18, z: 0.2 },
        rotation: { x: 0.14, y: -0.18, z: 0.07 },
        scale: { x: 0.84, y: 0.84, z: 0.84 },
      },
      sphere: {
        startX: -2.86,
        startY: 0.08,
        startZ: 0.26,
        nearX: -0.88,
        nearY: 0.05,
        nearZ: 0.12,
        crossX: -0.06,
        crossY: -0.01,
        crossZ: -0.05,
        hiddenX: 0.1,
        hiddenY: -0.05,
        hiddenZ: -0.12,
      },
      object: {
        startX: 0.17,
        startY: -0.08,
        startZ: -0.1,
        restX: 1.38,
        restY: -0.08,
        restZ: 0.07,
        holdX: 1.78,
        holdY: -0.02,
        holdZ: 0.09,
        exitX: 2.16,
        exitY: -0.11,
        exitZ: -0.07,
      },
    },
    mobile: {
      membrane: {
        position: { x: 0.1, y: -0.3, z: 0.21 },
        rotation: { x: 0.13, y: -0.15, z: 0.07 },
        scale: { x: 0.79, y: 0.79, z: 0.79 },
      },
      sphere: {
        startX: -2.32,
        startY: 0.04,
        startZ: 0.22,
        nearX: -0.74,
        nearY: 0.03,
        nearZ: 0.1,
        crossX: -0.04,
        crossY: -0.01,
        crossZ: -0.05,
        hiddenX: 0.08,
        hiddenY: -0.05,
        hiddenZ: -0.11,
      },
      object: {
        startX: 0.14,
        startY: -0.12,
        startZ: -0.08,
        restX: 1.12,
        restY: -0.13,
        restZ: 0.05,
        holdX: 1.44,
        holdY: -0.08,
        holdZ: 0.07,
        exitX: 1.76,
        exitY: -0.14,
        exitZ: -0.08,
      },
    },
  },
  cycle: {
    leadDelay: 0.04,
    approachDuration: 0.88,
    accelerateDuration: 0.34,
    translateDuration: 0.28,
    emergeDuration: 0.92,
    displayDuration: 0.18,
    settleDuration: 0.92,
    fadeDuration: 0.62,
    repeatDelay: 0.24,
  },
  ambientParticles: {
    introOpacityFloor: 0.82,
    pointerInfluence: 0.026,
    reducedMotionDriftScale: 0.3,
    reducedMotionCountScale: 0.66,
    coolTintMix: 0.24,
    intensity: {
      min: 0.66,
      max: 0.9,
      farFade: 0.88,
      nearFade: 1.06,
    },
    placement: {
      horizontalEdgeBias: 0.22,
      verticalJitter: 0.08,
      depthExponent: 0.92,
      zones: [
        {
          centerX: 0.34,
          centerY: -0.03,
          radiusX: 0.94,
          radiusY: 1.12,
          strength: 0.72,
          padding: 0.08,
        },
        {
          centerX: 1.7,
          centerY: 0.02,
          radiusX: 0.72,
          radiusY: 0.62,
          strength: 0.42,
          padding: 0.06,
        },
      ],
    },
    drift: {
      minX: 0.01,
      maxX: 0.024,
      minY: 0.008,
      maxY: 0.02,
      minZ: 0.004,
      maxZ: 0.012,
      minSpeed: 0.018,
      maxSpeed: 0.046,
      parallaxX: 0.02,
      parallaxY: 0.013,
      farMotionScale: 0.54,
      nearMotionScale: 0.72,
    },
    layouts: {
      desktop: {
        count: 14,
        minX: -2.84,
        maxX: 2.74,
        minY: -1.92,
        maxY: 2,
        minZ: -1.78,
        maxZ: -0.08,
        size: 0.074,
        opacity: 0.094,
      },
      laptop: {
        count: 12,
        minX: -2.54,
        maxX: 2.48,
        minY: -1.84,
        maxY: 1.9,
        minZ: -1.62,
        maxZ: -0.08,
        size: 0.07,
        opacity: 0.088,
      },
      tablet: {
        count: 7,
        minX: -2.08,
        maxX: 1.92,
        minY: -1.58,
        maxY: 1.66,
        minZ: -1.34,
        maxZ: -0.04,
        size: 0.064,
        opacity: 0.078,
      },
      mobile: {
        count: 5,
        minX: -1.72,
        maxX: 1.48,
        minY: -1.32,
        maxY: 1.36,
        minZ: -1.12,
        maxZ: -0.02,
        size: 0.058,
        opacity: 0.07,
      },
    },
  },
  motion: {
    stageFloatAmplitude: 0.022,
    stageFloatSpeed: 0.24,
    stageYawDrift: 0.014,
    pointerRotationX: 0.03,
    pointerRotationY: 0.06,
    pointerShiftX: 0.1,
    pointerShiftY: 0.06,
    cameraShiftX: 0.14,
    cameraShiftY: 0.1,
  },
  lights: {
    ambient: {
      color: "#eef2f7",
      intensity: 0.3,
    },
    hemisphere: {
      skyColor: "#7d92bb",
      groundColor: "#16110f",
      intensity: 0.24,
    },
    key: {
      color: "#d6e4ff",
      intensity: 1.7,
      position: { x: -3.6, y: 2.9, z: 4.8 },
    },
    rim: {
      color: "#93a8d8",
      intensity: 0.8,
      position: { x: 3.4, y: 1.8, z: 3.4 },
    },
    membraneAccent: {
      color: "#a9c2ff",
      intensity: 1.1,
      distance: 5.2,
      decay: 2,
      position: { x: 0.38, y: 0.12, z: 1.84 },
    },
  },
  reducedMotion: {
    interactionStrength: 0.06,
    motionScale: 0.24,
    cycleScale: 1.7,
  },
  fogDensity: 0.034,
};

export function getHeroViewportKey(width) {
  if (width <= heroConfig.quality.mobileBreakpoint) {
    return "mobile";
  }

  if (width <= heroConfig.quality.tabletBreakpoint) {
    return "tablet";
  }

  if (width <= heroConfig.quality.laptopBreakpoint) {
    return "laptop";
  }

  return "desktop";
}

export function resolveHeroMembraneConfig(viewportKey = "desktop") {
  const qualityProfile =
    heroConfig.membrane.qualityProfiles[viewportKey] ??
    heroConfig.membrane.qualityProfiles.desktop;

  return {
    ...heroConfig.membrane,
    appearance: {
      ...heroConfig.membrane.appearance,
      ...qualityProfile.appearance,
    },
    quality: {
      transmissionFloor: 0.6,
      idleTransmissionDriftScale: 1,
      bodyTransmissionDipScale: 1,
      bodyThicknessBoostScale: 1,
      bodyEnvBoostScale: 1,
      bodyEmissiveBoostScale: 1,
      rimEnvBoostScale: 1,
      rimOpacityBoostScale: 1,
      rimEmissiveBoostScale: 1,
      ...qualityProfile.dynamics,
    },
  };
}

export function getHeroResponsiveProfile(width, reducedMotion = false) {
  const viewportKey = getHeroViewportKey(width);
  const responsive = heroConfig.responsive[viewportKey];
  const isMobile = viewportKey === "mobile";
  const isTablet = viewportKey === "tablet";

  return {
    viewportKey,
    isMobile,
    isTablet,
    pixelRatioCap: responsive.pixelRatioCap,
    antialias: responsive.antialias,
    rendererPrecision: responsive.rendererPrecision,
    environmentMode: responsive.environmentMode,
    sphereDetail: {
      widthSegments: responsive.sphereDetail.widthSegments,
      heightSegments: responsive.sphereDetail.heightSegments,
    },
    interactionStrength: reducedMotion
      ? heroConfig.reducedMotion.interactionStrength
      : isMobile
        ? 0.42
        : isTablet
          ? 0.7
          : 1,
    motionScale: reducedMotion
      ? heroConfig.reducedMotion.motionScale
      : isMobile
        ? 0.7
        : isTablet
          ? 0.86
          : 1,
    cycleScale: reducedMotion ? heroConfig.reducedMotion.cycleScale : 1,
    camera: heroConfig.camera[viewportKey],
    chamber: heroConfig.chamber[viewportKey],
  };
}
