import * as THREE from "three";

export function createHeroMaterials(config) {
  const { palette } = config;
  const coolSheen = new THREE.Color(palette.cool).lerp(new THREE.Color(palette.lightWarm), 0.28);
  const warmSpecular = new THREE.Color(palette.lightWarm).lerp(new THREE.Color(palette.warm), 0.18);
  const coolSpecular = new THREE.Color(palette.lightWarm).lerp(new THREE.Color(palette.cool), 0.16);

  return {
    floor: new THREE.MeshPhysicalMaterial({
      color: palette.charcoal,
      metalness: 0.3,
      roughness: 0.78,
      clearcoat: 0.26,
      clearcoatRoughness: 0.54,
      envMapIntensity: 0.48,
    }),
    floorGlow: new THREE.MeshBasicMaterial({
      color: palette.warm,
      transparent: true,
      opacity: 0.075,
      blending: THREE.AdditiveBlending,
      depthWrite: false,
      side: THREE.DoubleSide,
      toneMapped: false,
    }),
    ribbon: new THREE.MeshPhysicalMaterial({
      color: "#d8d4d7",
      emissive: palette.cool,
      emissiveIntensity: 0.022,
      metalness: 0.96,
      roughness: 0.16,
      clearcoat: 1,
      clearcoatRoughness: 0.05,
      sheen: 0.7,
      sheenColor: coolSheen,
      sheenRoughness: 0.34,
      iridescence: 0.1,
      iridescenceIOR: 1.18,
      specularIntensity: 1,
      specularColor: warmSpecular,
      envMapIntensity: 1.82,
    }),
    membrane: new THREE.MeshPhysicalMaterial({
      color: "#f5f0ea",
      emissive: palette.cool,
      emissiveIntensity: 0.018,
      metalness: 0.03,
      roughness: 0.03,
      transmission: 0.97,
      thickness: 2.4,
      ior: 1.19,
      attenuationColor: palette.plumGlass,
      attenuationDistance: 1.9,
      clearcoat: 1,
      clearcoatRoughness: 0.025,
      iridescence: 0.18,
      iridescenceIOR: 1.18,
      iridescenceThicknessRange: [120, 520],
      specularIntensity: 1,
      specularColor: coolSpecular,
      transparent: true,
      opacity: 0.98,
      envMapIntensity: 1.72,
      side: THREE.DoubleSide,
    }),
    membraneEdge: new THREE.MeshPhysicalMaterial({
      color: "#d8d0cb",
      metalness: 0.82,
      roughness: 0.14,
      clearcoat: 1,
      clearcoatRoughness: 0.05,
      specularIntensity: 1,
      specularColor: warmSpecular,
      transparent: true,
      opacity: 0.38,
      envMapIntensity: 1.82,
    }),
    paneOutline: new THREE.MeshPhysicalMaterial({
      color: "#c9c2c5",
      metalness: 0.84,
      roughness: 0.24,
      clearcoat: 1,
      clearcoatRoughness: 0.1,
      transparent: true,
      opacity: 0.2,
      envMapIntensity: 1.1,
    }),
    courier: new THREE.MeshPhysicalMaterial({
      color: "#faf4ee",
      emissive: palette.cool,
      emissiveIntensity: 0.03,
      metalness: 0.04,
      roughness: 0.018,
      transmission: 0.99,
      thickness: 3.2,
      ior: 1.2,
      attenuationColor: palette.plumGlass,
      attenuationDistance: 1.55,
      clearcoat: 1,
      clearcoatRoughness: 0.018,
      iridescence: 0.22,
      iridescenceIOR: 1.16,
      iridescenceThicknessRange: [160, 700],
      specularIntensity: 1,
      specularColor: coolSpecular,
      transparent: true,
      opacity: 1,
      envMapIntensity: 2.08,
    }),
    sphereChrome: new THREE.MeshPhysicalMaterial({
      color: "#d4d0d3",
      metalness: 0.98,
      roughness: 0.12,
      clearcoat: 1,
      clearcoatRoughness: 0.06,
      iridescence: 0.08,
      iridescenceIOR: 1.16,
      envMapIntensity: 1.5,
    }),
    sphereGlass: new THREE.MeshPhysicalMaterial({
      color: "#f5ede5",
      metalness: 0.02,
      roughness: 0.04,
      transmission: 0.98,
      thickness: 1.7,
      ior: 1.14,
      attenuationColor: palette.plumGlass,
      attenuationDistance: 2.6,
      clearcoat: 1,
      clearcoatRoughness: 0.04,
      iridescence: 0.1,
      iridescenceIOR: 1.12,
      transparent: true,
      opacity: 0.98,
      envMapIntensity: 1.4,
    }),
    spherePearl: new THREE.MeshPhysicalMaterial({
      color: "#d8d4d1",
      emissive: palette.ember,
      emissiveIntensity: 0.02,
      metalness: 0.34,
      roughness: 0.22,
      clearcoat: 1,
      clearcoatRoughness: 0.08,
      sheen: 0.4,
      sheenColor: new THREE.Color(palette.lightWarm),
      sheenRoughness: 0.46,
      envMapIntensity: 1.12,
    }),
    backdrop: new THREE.MeshBasicMaterial({
      color: palette.plum,
      transparent: true,
      opacity: 0.14,
      blending: THREE.AdditiveBlending,
      depthWrite: false,
      side: THREE.DoubleSide,
      toneMapped: false,
    }),
    dust: new THREE.PointsMaterial({
      color: palette.lightWarm,
      size: 0.02,
      transparent: true,
      opacity: 0.28,
      sizeAttenuation: true,
      depthWrite: false,
      blending: THREE.AdditiveBlending,
      toneMapped: false,
    }),
  };
}

export function createHeroAssetMaterial(config, spec) {
  const tone = spec.materialTone ?? {};
  const { palette } = config;

  return new THREE.MeshPhysicalMaterial({
    color: tone.color ?? palette.metal,
    emissive: tone.emissive ?? palette.ember,
    emissiveIntensity: tone.emissiveIntensity ?? 0.04,
    metalness: tone.metalness ?? 0.58,
    roughness: tone.roughness ?? 0.24,
    clearcoat: tone.clearcoat ?? 0.92,
    clearcoatRoughness: tone.clearcoatRoughness ?? 0.1,
    sheen: tone.sheen ?? 0.42,
    sheenColor: tone.sheenColor ?? palette.lightWarm,
    sheenRoughness: tone.sheenRoughness ?? 0.46,
    iridescence: tone.iridescence ?? 0.08,
    iridescenceIOR: 1.25,
    specularIntensity: 0.92,
    specularColor: new THREE.Color(palette.lightWarm),
    transparent: true,
    opacity: 1,
    envMapIntensity: 1.34,
  });
}
